### ISSUE TITLE
nanoc check --list not listing all available checks

### ISSUE THREAD

**Issue by elomatreb** [nanoc/nanoc#928]
### Summary

If I run `bundle exec nanoc check --list`, nanoc does not list all available checks, although they are executed when using `--all` or calling them by name.

### Steps to reproduce

1. Create fresh nanoc site
2. Run `bundle exec nanoc check --list`

I have created a [demo repository](https://github.com/elomatreb/nanoc-bug-demo) for convenience.

### Expected behavior

All available checks are listed.

### Actual behavior

Some checks (e.g. the HTML and CSS checks) are not displayed, although there are some empty lines.

```
Loading site… done
Available checks:

  
  
  external_links
  internal_links
  mixed_content
  stale
```

### Details

Running nanoc version 4.2.4, Ruby 2.3.1 on linux.

**Comment by anton-tsyganenko** [comment]
I thing that it is related to another issue: when running `nanoc check -a` the output looks like:
```
Loading site… done
  Running check …                 ok
  Running check external_links…   error
  Running check …                 ok
  Running check internal_links…   ok
  Running check stale…            ok
  Running check mixed_content…    ok
Issues found!
<...>
```

**Comment by ddfreyne** [comment]
Fixed in #930. Thanks for reporting!

**Comment by anton-tsyganenko** [comment]
Output of `nanoc check --list` didn't change in Nanoc 4.3.0, `nanoc check --all`now chrashes at third check:
```
Loading site… done
  Running check …                 ok
  Running check external_links…   error
  Running check …                 
Captain! We’ve been hit!

Message:

Net::HTTPRetriableError: 302 "Found"

Compilation stack:

  (empty)

Stack trace:

  0. /usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
  1. /usr/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
  2. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/validator.rb:88:in `send_request'
  3. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/validator.rb:85:in `send_request'
  4. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/markup_validator.rb:131:in `validate'
  5. /home/anton/.gem/ruby/2.3.0/gems/w3c_validators-1.2/lib/w3c_validators/markup_validator.rb:117:in `validate_file'
  6. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:8:in `block in run'
  7. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:7:in `each'
  8. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/checks/w3c_validator.rb:7:in `run'
  9. /home/anton/.gem/ruby/2.3.0/gems/nanoc-4.3.0/lib/nanoc/extra/checking/runner.rb:120:in `block in run_checks'
  ... 20 more lines omitted. See full crash log for details.

If you believe this is a bug in Nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
```

Request re-open.

**Comment by elomatreb** [comment]
I can confirm the checks still not showing up correctly, and I get the same error as above when running the `html` check.

Additionally, the `css` check [is failing](https://gist.github.com/elomatreb/21b98107585d83b1ea62e6a60bd59378) in a similar way. I was already getting this error before the update to 4.3, but I assumed it was caused by something I did wrong.

I noticed that both of these errors appear to come from the `w3c_validators` gem, so maybe this is not a nanoc problem?

**Comment by ddfreyne** [comment]
This’ll end up in 4.3.1; I only made the fix after releasing 4.3.0.

**Comment by ddfreyne** [comment]
This is now released in 4.3.1.

**Comment by ddfreyne** [comment]
@anton-tsyganenko Sorry—I did not see that you indicated a separate issue. I’ve created a new issue for the problem you mentioned: #943.
