### ISSUE TITLE
Getting "Killed" on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by RubenVerborgh** [nanoc/nanoc#972]
### Summary

Running nanoc 4.3.7 (as well as 4.3.2) stops at random moments, emitting "Killed".

### Steps to reproduce

1. Use Ubuntu 16.04.1 LTS
2. Load my site (code not public but available on request)
3. Execute "bundle exec nanoc co"

### Expected behavior

The site compiles.
If an error occurs, I get a stack trace.

### Actual behavior

At random moments in the compilation process, I'm receiving a "Killed" message.

### Details

Sometimes compilation succeeds. Used to work perfectly on other Linuxes on OSX.

### Crash log

None.

**Comment by RubenVerborgh** [comment]
I would have tried to find a MWE, but that's hard without a stack trace.

**Comment by ddfreyne** [comment]
Which version of Ruby are you running?

`lib/nanoc/cli/commands/compile.rb` does some icky tricks with the GC in order to speed up compilation. Usually the icky trick does a remarkable job, but perhaps it’s blowing up in your case. Can you change `GCController.enable_for?` to return false, and see whether the problem persists?

**Comment by RubenVerborgh** [comment]
Running Ruby 2.3.1p112.

Changed it to `true`, ran it 5 times successively, the issue did not occur anymore. (Not a guarantee, however, as the issue does not always occur in general.)

**Comment by ddfreyne** [comment]
Fix in #975.

**Comment by RubenVerborgh** [comment]
Thanks! And interesting about the speed increase 😄

**Comment by RubenVerborgh** [comment]
@ddfreyne Still getting killed occasionally. Could we reopen this?

**Comment by ddfreyne** [comment]
Okay :(

**Comment by ddfreyne** [comment]
Do you have large files that you load in memory in your site? Memory usage is the only thing that I can think of right now…

**Comment by RubenVerborgh** [comment]
I don't really have large files, and certainly not loading them in memory. However, it might be related to memory somehow: when I have `htop` open, CPU initially rises to 26.5% (of 1GB RAM), and then briefly hits 33.3% or so before crashing.

Can I do anything to make more relevant debugging output visible?

**Comment by ddfreyne** [comment]
I’m regularly getting “killed” errors on Travis CI now, so I’ll investigate and fix those, hoping that it’ll also benefit your case.

**Comment by RubenVerborgh** [comment]
😮  Interesting. Note: I starting having these when switching to a new VM (latest version of everything); maybe Travis is in a similar condition.

**Comment by ddfreyne** [comment]
Two changes that made the Travis CI build more reliable:

* https://github.com/nanoc/nanoc/commit/de2a354a124d965c1d8b7a3a624edfc163c237f8 — use conservative memory options
* https://github.com/nanoc/nanoc/commit/3cb7ce8750975ecebd067a7ddea1cd4e9076aa1a — remove test that soaks up memory

Not sure how much this helps. My assumption is that “killed” in your case is related to memory usage.

**Comment by RubenVerborgh** [comment]
How could we prove / fix that?

**Comment by ddfreyne** [comment]
Unsure. I’m also unsure as to what kills the process (it’s not `ruby` itself that does the killing). How much mem have you assigned to your VM? How much swap does it have?

**Comment by RubenVerborgh** [comment]
1GB of RAM; swap unknown (it's a container).

Compilation works properly at the moment, after a reboot.

**Comment by ddfreyne** [comment]
Removing this from the 4.3.8 milestone as it does not occur reliably, memory options help, and workaround are available (increasing available memory). Will keep it open, however!

**Comment by RubenVerborgh** [comment]
Seeing it less recently since upgrading to latest Nanoc.

**Comment by RubenVerborgh** [comment]
This issue can be closed as far as I'm concerned.

**Comment by ddfreyne** [comment]
I’ll close this, as I believe it’s not a bug in Nanoc and can/should be resolved by increasing available memory for Nanoc. (Nanoc’s memory usage will continue to decrease, but that’s not directly related to this issue.)

**Comment by ddfreyne** [comment]
The improvements to reduce memory usage in Nanoc 4.6.1 should have made this better!

**Comment by RubenVerborgh** [comment]
Thanks, will upgrade and test. (The issue still occurs every now and then; `rm -r tmp` and recompiling helps.)

**Comment by ddfreyne** [comment]
4.6.1 is a couple of months old and I forgot to follow up. 4.7.4 is the current release and might also help.
